"""PDF report export formatter using ReportLab."""

import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

from app.export.formatters.base import BaseExportFormatter
from app.export.models import ExportResult


class PdfExportFormatter(BaseExportFormatter):
    """Formats canonical report data into a professional PDF document."""

    def format_report(
        self, report_data: dict[str, Any], session_id: str
    ) -> ExportResult:
        """Format report data dictionary into PDF document bytes."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()

        # Custom typography styles
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1E293B"),
            spaceAfter=10,
        )

        subtitle_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=15,
        )

        h2_style = ParagraphStyle(
            "ReportH2",
            parent=styles["Heading2"],
            fontSize=15,
            leading=19,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=14,
            spaceAfter=6,
        )

        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["BodyText"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
            spaceAfter=8,
        )

        summary_box_style = ParagraphStyle(
            "SummaryBox",
            parent=styles["BodyText"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1E293B"),
            backColor=colors.HexColor("#F8FAFC"),
            borderColor=colors.HexColor("#CBD5E1"),
            borderWidth=1,
            borderPadding=10,
            spaceAfter=15,
        )

        source_style = ParagraphStyle(
            "SourceItem",
            parent=styles["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#2563EB"),
            spaceAfter=4,
        )

        story: list[Any] = []

        # 1. Header & Title
        title_text = report_data.get("title", "Desearch AI Research Report")
        story.append(Paragraph(title_text, title_style))
        story.append(
            Paragraph(
                f"Generated by Desearch AI | Session ID: {session_id[:8]}...",
                subtitle_style,
            )
        )
        story.append(
            HRFlowable(
                width="100%",
                thickness=1,
                color=colors.HexColor("#E2E8F0"),
                spaceAfter=15,
            )
        )

        # 2. Executive Summary
        exec_summary = report_data.get("executive_summary", "")
        if exec_summary:
            story.append(Paragraph("<b>Executive Summary</b>", h2_style))
            # Clean HTML characters in text for ReportLab Paragraph
            safe_summary = (
                exec_summary.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            )
            story.append(Paragraph(safe_summary, summary_box_style))

        # 3. Report Sections
        sections = report_data.get("sections", [])
        if sections:
            for sec in sections:
                sec_title = (
                    sec.get("title", "")
                    .replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                )
                sec_content = (
                    sec.get("content", "")
                    .replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                    .replace("\n", "<br/>")
                )

                if sec_title:
                    story.append(Paragraph(sec_title, h2_style))
                if sec_content:
                    story.append(Paragraph(sec_content, body_style))
                story.append(Spacer(1, 6))

        # 4. Sources & References
        sources = report_data.get("sources_cited", [])
        if sources:
            story.append(Spacer(1, 10))
            story.append(Paragraph("Sources & Citations", h2_style))
            story.append(
                HRFlowable(
                    width="100%",
                    thickness=0.5,
                    color=colors.HexColor("#CBD5E1"),
                    spaceAfter=10,
                )
            )
            for src in sources:
                safe_src = (
                    str(src).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                )
                story.append(Paragraph(f"• {safe_src}", source_style))

        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()

        filename = self.sanitize_filename(title_text, session_id, "pdf")

        return ExportResult(
            content=pdf_bytes,
            media_type="application/pdf",
            filename=filename,
        )
